//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestePratico_crud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Endereco
    {
        public int Identificador { get; set; }
        public int IdentificadorCliente { get; set; }
        public string Logradouro { get; set; }
        public string Numero { get; set; }
        public string Complemento { get; set; }
        public string Cidade { get; set; }
        public string UF { get; set; }
        public string CEP { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
